<template>
  <div class="page-shell">
    <header class="page-head"><div><span class="page-kicker">ASSET TRANSFER</span><h2>资产调拨</h2><p>管理闲置资产调拨建议，接收部门确认后由管理员执行。</p></div><el-button type="primary" @click="dialog=true">新建调拨建议</el-button></header>
    <div class="tech-card">
      <div class="toolbar"><el-radio-group v-model="status" @change="changeStatus"><el-radio-button label="">全部</el-radio-button><el-radio-button label="pending_receiver">待确认</el-radio-button><el-radio-button label="confirmed">待执行</el-radio-button><el-radio-button label="completed">已完成</el-radio-button></el-radio-group><span class="result-count">共 {{ total }} 条调拨记录</span></div>
      <el-table :data="rows" v-loading="loading" stripe empty-text="当前状态下暂无调拨建议"><el-table-column prop="asset_id" label="资产ID" width="100"/><el-table-column prop="source_dept_name" label="原部门" min-width="140" show-overflow-tooltip/><el-table-column prop="target_dept_name" label="接收部门" min-width="140" show-overflow-tooltip/><el-table-column prop="target_position" label="目标位置" min-width="130" show-overflow-tooltip/><el-table-column prop="target_user_name" label="使用人" width="110"/><el-table-column prop="status" label="状态" width="110"><template #default="{row}"><el-tag :type="statusType[row.status]">{{labels[row.status]||row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="240" fixed="right"><template #default="{row}"><el-button v-if="row.status==='pending_receiver'" link type="success" @click="decide(row,true)">确认接收</el-button><el-button v-if="row.status==='pending_receiver'" link type="danger" @click="decide(row,false)">拒绝</el-button><el-button v-if="row.status==='confirmed'&&isAdmin" link type="primary" @click="execute(row)">执行调拨</el-button><el-button v-if="['pending_receiver','confirmed'].includes(row.status)" link @click="cancel(row)">取消</el-button></template></el-table-column></el-table>
      <el-pagination v-if="total" background layout="total,prev,pager,next" :total="total" :page-size="20" :current-page="page" @current-change="p=>{page=p;load()}"/>
    </div>
    <el-dialog v-model="dialog" title="新建调拨建议" width="560px"><el-alert title="提交后将进入接收部门确认流程" type="info" :closable="false" show-icon/><el-form class="dialog-form" label-position="top"><div class="form-grid"><el-form-item label="资产ID" required><el-input-number v-model="form.asset_id" :min="1" controls-position="right"/></el-form-item><el-form-item label="接收部门" required><el-select v-model="form.target_dept_id" filterable placeholder="请选择接收部门"><el-option v-for="d in depts" :key="d.dept_id" :label="d.dept_name" :value="d.dept_id"/></el-select></el-form-item><el-form-item label="目标位置"><el-input v-model="form.target_position" placeholder="请输入资产目标位置"/></el-form-item><el-form-item label="使用人"><el-input v-model="form.target_user_name" placeholder="请输入使用人"/></el-form-item></div><el-form-item label="建议理由"><el-input v-model="form.reason" type="textarea" :rows="3" placeholder="说明调拨背景和建议依据"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">提交确认</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import {ref,reactive,computed,onMounted} from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import {getTransferSuggestions,createTransferSuggestion,confirmTransfer,rejectTransfer,executeTransfer,cancelTransfer,getDepartments} from '@/api';import {useUserStore} from '@/store';
const store=useUserStore(),isAdmin=computed(()=>store.user?.is_admin==1),rows=ref([]),depts=ref([]),total=ref(0),page=ref(1),status=ref(''),loading=ref(false),saving=ref(false),dialog=ref(false),labels={pending_receiver:'待确认',confirmed:'待执行',completed:'已完成',rejected:'已拒绝',cancelled:'已取消',draft:'草稿'},statusType={pending_receiver:'warning',confirmed:'primary',completed:'success',rejected:'danger',cancelled:'info',draft:'info'},form=reactive({asset_id:null,target_dept_id:null,target_position:'',target_user_name:'',reason:''});
const load=async()=>{loading.value=true;try{const r=await getTransferSuggestions({status:status.value||undefined,page:page.value,size:20});rows.value=r.list;total.value=r.total}finally{loading.value=false}};const changeStatus=()=>{page.value=1;load()};const create=async()=>{if(!form.asset_id||!form.target_dept_id){ElMessage.warning('请填写资产ID和接收部门');return}saving.value=true;try{await createTransferSuggestion(form);ElMessage.success('调拨建议已提交');dialog.value=false;load()}finally{saving.value=false}};const decide=async(r,a)=>{try{await ElMessageBox.confirm(a?'确认接收该资产？':'确认拒绝该建议？');a?await confirmTransfer(r.id):await rejectTransfer(r.id);ElMessage.success(a?'已确认接收':'已拒绝');load()}catch{}};const execute=async r=>{try{await ElMessageBox.confirm('执行后将更新资产归属信息，是否继续？');await executeTransfer(r.id);ElMessage.success('调拨已执行');load()}catch{}};const cancel=async r=>{try{await ElMessageBox.confirm('确认取消该调拨建议？');await cancelTransfer(r.id);ElMessage.success('调拨建议已取消');load()}catch{}};onMounted(async()=>{depts.value=await getDepartments();load()});
</script>
<style scoped>.page-shell{display:grid;gap:16px}.page-head{display:flex;align-items:flex-end;justify-content:space-between}.page-kicker{font-size:11px;letter-spacing:1.6px;color:#1769aa}.page-head h2{margin:4px 0 6px;font-size:24px}.page-head p,.result-count{color:#718198;font-size:13px}.toolbar{justify-content:space-between}.el-pagination{justify-content:flex-end;margin-top:16px}.dialog-form{margin-top:18px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.form-grid :deep(.el-input-number),.form-grid :deep(.el-select){width:100%}</style>
